config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root 'events#index'

  resources :events do
      member do
        get 'rsvp'
        get 'cancel_rsvp'
      end
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord

    belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
    has_many :event_users
    has_many :attendees, through: :event_users, source: :user
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, :foreign_key => 'creator_id', :class_name => 'Event', dependent: :delete_all
  has_many :event_users, dependent: :delete_all
  has_many :attended_events, through: :event_users, source: :event, dependent: :delete_all

  validates :name, presence: true, length: { minimum: 2 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.order(eventdate: :desc)

  end

  def show
      @event = Event.find(params[:id])
  end

  def new
    @event = Event.new()
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to :events, allow_other_host: true
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])

  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
      flash[:notice] = 'Event updated successfully'
    else
      render 'edit'
    end

  end


  def rsvp
      @event = Event.find(params[:id])
      if @event.attendees.include?(current_user)
        redirect_to @event, notice: "You are already on the list"
      else
        @event.attendees << current_user
        redirect_to @event, notice: "You have successfully rsvp-ed"
      end
  end

  def cancel_rsvp
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    redirect_to @event, notice: "You are no longer attending this event"
  end




  private

  def event_params
    params.require(:event).permit(:eventdate, :eventname, :eventdesc)
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
    @events = @user.created_events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_user_helper.rb
module EventUserHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_eventtemplate.html.erb
<div class="event">
    <div class="event-item-heading"><%= event.eventname %></div>
    <div class="event-item-date"><%= event.eventdate %></div>
    <% @user = User.find(event.creator_id) %>
    <div class="event-item-creator"><%= @user.email %></div>
    <%= link_to "See details", event_path(event.id) %>

</div>
<% end %>

app/views/events/_topnav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
<div class="container-fluid">
<%= link_to "Evently", root_path, class: "navbar-brand" %>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to "Profile", edit_user_registration_path(current_user.id), class: "nav-link" %>
    </li>
    <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">Events</a>
        <ul class="dropdown-menu">
          <li><%= link_to "My Events", user_path(current_user.id), class: "dropdown-item" %></li>
          <li><%= link_to "Create New Event", new_event_path, class: "dropdown-item" %></li>
        </ul>
    </li>
    <li class="nav-item">
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
  <form class="d-flex" role="search">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
</div>
</div>
</nav>

app/views/events/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Event</title>
</head>
<body>
    <%= render 'topnav' %>
    <div class="row py-5">
        <div class="col-lg-4 mx-auto">
            <section class="d-flex justify-content-center mt-5 mb-5">
                <span class="text-capitalize text-white bg-dark px-2 py-1 rounded">
                    Edit Event Details
                </span>
            </section>

            <%= form_with model: @event do |form| %>
                <div class="field mt-3">
                    <%= form.label :eventname, "Event Name" %>
                    <%= form.text_field :eventname, class: "form-control py-2"%>
                </div>
                <div class="field mt-3">
                    <%= form.label :eventdesc, "Event Description" %>
                    <%= form.text_area :eventdesc, class: "form-control py-2" %>
                </div>
                <div class="field mt-3">
                    <%= form.label :eventdate, "Event Date" %>
                    <%= form.date_select :eventdate, class: "form-control py-2" %>
                </div>
                <div class="actions mt-4 mb-5">
                    <%= form.submit "Update", class: "form-control py-2 btn btn-success fw-bold shadow" %>
                </div>
                <%= link_to "Cancel", user_path(current_user.id), class: "form-control py-2 btn btn-danger fw-bold shadow" %>
            <% end %>

        </div>
    </div>

</body>
</html>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Evently</title>
</head>
<body>
    <%= render 'topnav' %>

    <div class="container text-center mt-5">
      <div class="row gx-5">
        <% @events.each do |event| %>
        <div class="col-lg-4 d-flex align-items-stretch">
            <div class="card d-block w-100" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title"><%= event.eventname %></h5>
                  <% @user = User.find(event.creator_id) %>
                  <h6 class="card-subtitle mb-2 text-muted"><%= @user.name %></h6>
                  <p class="card-text"><%= event.eventdesc %><br><%= event.eventdate %></p>
                  <%= link_to "See details", event_path(event.id), class: "card-link"%>
                </div>
            </div>
        </div>
        <% end %>
      </div>

    </div>

</body>
</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <%= render 'topnav' %>
    <div class="row py-5">
        <div class="col-lg-4 mx-auto">
            <section class="d-flex justify-content-center mt-5 mb-5">
                <span class="text-capitalize fw-bold bg-light px-2 py-1 rounded">
                    Create New Event
                </span>
            </section>

            <%= form_with model: @event do |form| %>
                <div class="field mt-3">
                    <%= form.text_field :eventname, placeholder: "Event Name", class: "form-control py-2"%>
                </div>
                <div class="field mt-3">
                    <%= form.text_area :eventdesc, placeholder: "Event Description", class: "form-control py-2" %>
                </div>
                <div class="field mt-3">
                    <%= form.date_select :eventdate, placeholder: "Event Date", class: "form-control py-2" %>
                </div>
                <div class="actions mt-4 mb-5">
                    <%= form.submit "Create", class: "form-control py-2 btn btn-success fw-bold shadow" %>
                </div>
                <%= link_to "Cancel", user_path(current_user.id), class: "form-control py-2 btn btn-danger fw-bold shadow" %>
            <% end %>

        </div>
    </div>
</body>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Show Event</title>
</head>
<body>

        <%= render 'topnav' %>
        <% @user = User.find(@event.creator_id) %>
        <div class="container mt-5">
        <div class="row mb-4 mt-5 mx-auto">
            <div class="col">
                <h1><%= @event.eventname %></h1>
            </div>
            <div class="col text-right">
                <% if current_user.id != @user.id %>
                  <% if @event.attendees.include?(current_user) %>
                    <%= link_to "Cancel RSVP", cancel_rsvp_event_path, class: "btn btn-outline-secondary" %>
                  <% else %>
                    <%= link_to 'RSVP', rsvp_event_path, class: "btn btn-primary" %>
                  <% end %>
                <% else %>
                    <%= link_to 'Edit Event', edit_event_path(@event.id), class: "btn btn-outline-secondary" %>
                <% end %>
            </div>

        </div>
        <div class="row mb-4 mx-auto">
            <div class="col">
                <div class="card">
                    <div class="row no-gutters">
                        <div class="col-md-8">
                            <div class="card-body">
                                <p class="card-text text-muted"><%= @event.eventdesc %></p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card-body">
                                <p class="text-muted">Created by <%= @user.name %></p>
                                <p class="text-muted">
                                    <%= @event.eventdate %>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>






</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evently</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </head>

  <body>
      <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <%= render 'events/topnav' %>
    <div class="container-fluid">
    <h3 class="mt-3">Created Events:</h3>
    <div class="container text-center mt-5">

      <div class="row gx-5">
        <% @events.each do |event| %>
        <div class="col-sm-5">

            <div class="card d-block w-100" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title"><%= event.eventname %></h5>
                  <% @user = User.find(event.creator_id) %>
                  <h6 class="card-subtitle mb-2 text-muted"><%= @user.name %></h6>
                  <p class="card-text"><%= event.eventdesc %><br><%= event.eventdate %></p>
                  <%= link_to "See details", event_path(event.id), class: "card-link"%>
                </div>
            </div>

        </div>
        <% end %>
      </div>
    </div>
    <h3 class="mt-3">Attended Events:</h3>
    <div class="container text-center mt-5">
      <div class="row gx-5">
        <% current_user.attended_events.each do |event| %>
        <div class="col-sm-5">
            <div class="card d-block w-100" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title"><%= event.eventname %></h5>
                  <% @user = User.find(event.creator_id) %>
                  <h6 class="card-subtitle mb-2 text-muted"><%= @user.name %></h6>
                  <p class="card-text"><%= event.eventdesc %><br><%= event.eventdate %></p>
                  <%= link_to "See details", event_path(event.id), class: "card-link"%>
                </div>
            </div>
        </div>
        <% end %>
      </div>

    </div>

</div>






</body>
</html>